server.type=local

jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://175.212.202.74:11433;database=finereport;
jdbc.user=finereport
jdbc.password=spotfire

winker.primary.host=localhost
winker.primary.port=9000
winker.backup.host=localhost
winker.backup.port=9000

# 안전작업허가서 API
api.mes.safety-work-permit={ip:port}/exapp/v1/she/work-permit

api.test=https://httpbin.org/post

# 안전 검사 관리 API
api.mes.safety-inspection={ip:port}/exapp/v1/she/safety-period

## MES API HEADER 정보 ##
header.content-type=application/json; charset=UTF-8
header.accept = application/json
header.x-certkey=3d8f1e2a-7c45-4b6a-8f2d-5c1a9e7b3d21
header.x-uuid=a12c45f0-9bd3-4e7a-b8c1-0f2a9d6c3e54
# 전문 구분 (81: 수집 전문, 82: 알람)
header.x-commandtype = 81

api.mes.test=https://jsonplaceholder.typicode.com/posts